-define(VERSION, "http://github.com/gdamjan/erlang-irc-bot").
-define(REALNAME, "An experimental Erlang IRC bot").
-define(QUITMSG, "I can feel it, my mind is going...").
-define(SEND_TIMEOUT, 10000). % 10sec
-define(CONNECT_TIMEOUT, 60000). % 60sec
-define(KEEPALIVE, 60000). % 1min
