name: Release

on:
  release:
    types: [created]

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          rebar3-version: "3"

      - name: Cache rebar3 dependencies
        uses: actions/cache@v6
        with:
          path: ~/.cache/rebar3
          key: rebar3-${{ hashFiles('rebar.lock') }}
          restore-keys: rebar3-

      - name: Build prod release tarball
        run: rebar3 as prod tar

      - name: Upload release artifact
        uses: softprops/action-gh-release@v3
        with:
          #prerelease: false
          files: |
            _build/prod/rel/ircbot/ircbot-*.tar.gz
